Support other languages
stair-lab/melt pull request #16
Opened 2024-08-03 11:34 UTC by ledong0110

- Format data standard
- Metric configuration
- Language specific configuration

**Progress**:
- Complete 9 scenarios except IR task

2024-08-03 11:36 UTC, ledong0110 commented
Please help me verify the pipeline and wait for updating IR task

2024-08-03 14:00 UTC, martinakaduc requested changes
I think we need to update readme.

2024-08-03 14:00 UTC, martinakaduc commented on config/vi/llm_template.json
LLM Template should be at root of `config` folder.

2024-08-03 14:00 UTC, martinakaduc commented on config/vi/summac_model.json
I think this file should be in the root of `config` folder.

2024-08-03 17:44 UTC, sangttruong commented
Too many files have changed -- could you provide a tutorial or a readme for others to understand the code structure?

2024-08-09 15:00 UTC, sangttruong commented
@ledong0110 please resolve the conflict

2024-08-18 16:18 UTC, merged